version: "2" # docker-compose version number

volumes:
  config-volume:

services:
  config:
    # helper container for copying configuration data to the config-volume
    build: ./config
    volumes:
      - config-volume:/usr/src/config

  mqtt_broker:
    # https://github.com/ray-hrst/mosquitto.git
    build: ./mosquitto/docker/1.6
    # image: arm32v6/eclipse-mosquitto
    depends_on:
      - config
    ports: 
      - "1883:1883" # HOST:CONTAINER
      - "9001:9001" # HOST:CONTAINER
    volumes:
      - config-volume:/mosquitto/config/ # SOURCE:TARGET
